Models/ViewModels/AllProductsViewModel.cs
using myproject.Models.Dtos;

namespace myproject.Models.ViewModels
{
    public class AllProductsViewModel
    {
        public string? Title {get; set;}
        public IEnumerable<Product> AllProducts {get; set;} = new List<Product>();
    }
}

Models/ViewModels/ContactViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace myproject.Models.ViewModels
{
    public class ContactViewModel
    {

        [Display(Name = "First Name")]
        [Required(ErrorMessage = "This field is required")]
        public string FirstName {get; set;} = null!;

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "This field is required")]
        public string LastName {get; set;} = null!;

        [Display(Name = "Email")]
        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", ErrorMessage = "Email address is not formatted correctly")]
        public string Email {get; set;} = null!;

        [Required(ErrorMessage = "This field is required")]
        public string Message {get; set;} = null!;

    }
}

Models/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace myproject.Models.ViewModels
{
    public class LoginViewModel
    {
        [DataType(DataType.EmailAddress)]
        public string Email {get; set;} = null!;


        [DataType(DataType.Password)]
        public string Password {get; set;} = null!;

        public bool RememberMe {get; set;}
    }
}

Controllers/ContactController.cs
using myproject.Models.ViewModels;
using myproject.Helpers.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace myproject.Controllers
{
    public class ContactController : Controller
    {
        private readonly ContactRepo _contactRepo;
        public ContactController(ContactRepo contactRepo)
        {
            _contactRepo = contactRepo;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task <IActionResult> Index(ContactViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await _contactRepo.AddAsync(new Models.Entities.ContactFormEntity
                {
                    FirstName = viewModel.FirstName,
                    LastName = viewModel.LastName,
                    Email = viewModel.Email,
                    Message = viewModel.Message
                }
                );
                return RedirectToAction("Index");
            }
            return View(viewModel);
        }
    }
}

Controllers/LoginController.cs
using myproject.Helpers.Services;
using myproject.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;

namespace myproject.Controllers
{
    public class LoginController : Controller
    {
        private readonly AuthenticationService _authenticationService;

        public LoginController(AuthenticationService authenticationService)
        {
            _authenticationService = authenticationService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(LoginViewModel viewModel)
        {
            if (ModelState.IsValid && viewModel.Email.Contains("administrator")) 
            {
                if (await _authenticationService.LoginUserAsync(viewModel))
                {
                        return RedirectToAction("Index", "Administrator");
                }
                
            }
            else if (ModelState.IsValid)
            {
                if (await _authenticationService.LoginUserAsync(viewModel))
                {
                    return RedirectToAction("Index", "User");
                }


            }
            if (ModelState.IsValid)
            { 
            if  (!await _authenticationService.LoginUserAsync(viewModel))
                
                return RedirectToAction("Index", "AccessDenied");
            }



            return View(viewModel);
        }
    }
}

Controllers/RegistrationController.cs
using myproject.Helpers.Services;
using myproject.Models.Entities;
using myproject.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace myproject.Controllers
{
    public class RegistrationController : Controller
    {
        private readonly UserManager<UserEntity> _userManager;
        private readonly AuthenticationService _authenticationService;
        public RegistrationController(UserManager<UserEntity> userManager, AuthenticationService authenticationService)
        {
            _userManager = userManager;
            _authenticationService = authenticationService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(RegisterViewModel viewModel)
        {
            if(ModelState.IsValid)
            {
                if (!await _userManager.Users.AnyAsync(x => x.Email == viewModel.Email))
                {
                    if(await _authenticationService.RegisterUserAsync(viewModel))
                    return RedirectToAction("Index", "Login");
                }
                else
                    ModelState.AddModelError("", "A user with this email already exists");
            }
            return View(viewModel);
        }
    }
}

Views/Partials/_AllProducts.cshtml
@model AllProductsViewModel

<section class="collection">
    <div class="container">

        <h1 class="products-title">@Model.Title</h1>

        <div class="collection-grid">
            @foreach (var product in Model.AllProducts)
            {
                <a asp-action="Index" asp-controller="ProductDetails" asp-route-articleNumber="@product.ArticleNumber" class="collection-item">
                    <img class="headphones-image" src="@product.ImageUrl" alt="Poster" />
                    <div class="body">
                        <div class="title">@product. @product.ProductName</div>
                        
                        <div class="info">
                            <div class="price">@product.Price SEK</div>
                            <i class="add-cart fa-solid fa-cart-plus"></i>
                        </div>
                    </div>
                </a>
                
            }
        </div>
    </div>
</section>

Views/Partials/_BackOffice.cshtml
@inject UserAdminService userAdminService


@* <partial name="/Views/Partials/_SignedInHeader.cshtml" /> *@
<div class="container-bo min-vh-100">
    <div>
        <h2 class="bo-title">Backoffice roles: </h2>

        

        @foreach (var user in await userAdminService.GetUsersAsync())
        {



            <div class="roles-container">
                <div class="assigned-role"> @user.Email </div>
                

                @foreach (var role in user.NameOfRoles)
                {
                    <div class="assigned-title">@role</div>
                }

            </div>
        }
    </div>
</div>

Views/Partials/_Contact.cshtml
@model ContactViewModel

<div class="container">
    <div class="contact-container">
        <div class="col-6">
            <form method="post" asp-action="Index" asp-controller="Conrtacts" novalidate>
                <div class="mb-3">
                <label asp-for="FirstName" class="form-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="small text-danger"></span>
                </div>

            <div class="mb-3">
                    <label asp-for="LastName" class="form-label"></label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="small text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Email" class="form-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="small text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Message" class="form-label"></label>
                    <textarea asp-for="Message" class="form-control" rows="6"> </textarea>
                    <span asp-validation-for="Message" class="small text-danger"></span>
                </div>

                <div class="mt-3">
                    <button class="btn btn-success">Submit</button>
                </div>

            </form>
        </div>
    </div>
</div>

Views/Partials/_Footer.cshtml
<footer>
    <div class="container">
        © @DateTime.Now.Year Josefin. All right reserved.
    </div>
</footer>

Views/Partials/_Header.cshtml
<header>
    <div class="container">
        <nav id="menu" class="menu-links">
            <a class="menu-item" asp-controller="Home" asp-action="index">Home</a>
            <a class="menu-item" asp-controller="Products" asp-action="index">Products</a>
            <a class="menu-item" asp-controller="Contact" asp-action="index">Contact</a>
        </nav>

        <div class="toggle">
            <button class="btn-toggle" data-option="toggle" data-target="#menu">
                
            </button>
        </div>
    </div>
</header>

Views/Partials/_Login.cshtml
@model LoginViewModel

<div class="container">
    <div class="d-flex justify-content-center align-items-center min-vh-100">
    <div class="col-6">
        <form asp-action="Index" asp-controller="Login" method="post" novalidate>
            <div class="mb-3">
                <label asp-for="Email" class="form-label"></label>
                <input asp-for="Email" class="form-control" onkeyup="validateEmail" />
                <small><span asp-validation-for="Email" class="text-danger"></span></small>
            </div>

            <div class="mb-3">
                <label asp-for="Password" class="form-label"></label>
                <input asp-for="Password" class="form-control" onkeyup="validatePassword" />
                <small><span asp-validation-for="Password" class="text-danger"></span></small>
            </div>

            <div class="rememberme">
                    
                    <input type="checkbox" asp-for="RememberMe" />
                    <label asp-for="RememberMe"> Remember Me</label>
            </div>

            <div class="d-grid mb-5">
                <button type="submit" class="btn btn-success mt-2">Login</button>
            </div>

        </form>
    </div>

</div>
</div>

Views/Partials/_ProductDetails.cshtml
@using myproject.Models.Dtos;

@model Product

<div class="container">
    <div class="product-details-container">
    
        <img class="product-details-img" src="@Model.ImageUrl" alt="A picture of headphones"/>
        <div class="product-details-wrapper">
            <div class="product-details-details"> @Model.ProductName</div>

            <div class="product-details-details">@Model.Ingress</div>

            <div class="product-details-details">@Model.Description</div>
            <div class="product-details-details">Price: @Model.Price SEK</div>
        
        </div>

    </div>
</div>

Views/Partials/_ProductsByTag.cshtml
@model ProductsByTagViewModel;

﻿<section class="best-collection my-4">
    <div class="container">
        <h1 class="products-title">@Model.Title</h1>

        <div class="collection-grid">
            @foreach (var product in Model.NewProducts)
            {
                <a asp-action="Index" asp-controller="ProductDetails" asp-route-articleNumber="@product.ArticleNumber" class="collection-item">
                    <img class="poster-image" src="@product.ImageUrl" alt="Posters" />
                    <div class="body">
                        <div class="title"> @product.ProductName</div>
                        
                        <div class="info">
                            <div class="price">@product.Price SEK</div>
                            <i class="add-cart fa-solid fa-cart-plus"></i>
                        </div>
                    </div>
                </a>
                
            }
        </div>
        <div class="collection-grid">
            @foreach (var product in Model.PopularProducts)
            {
                <a asp-action="Index" asp-controller="ProductDetails" asp-route-articleNumber="@product.ArticleNumber" class="collection-item">
                    <img class="poster-image" src="@product.ImageUrl" alt="Posters">
                    <div class="body">
                        <div class="title"> @product.ProductName</div>
                        <div class="info">
                            <div class="price">@product.Price SEK</div>
                            <i class="add-cart fa-solid fa-cart-plus"></i>
                        </div>
                    </div>
                </a>

            }
        </div>
                <div class="collection-grid">
            @foreach (var product in Model.FeaturedProducts)
            {
                <a asp-action="Index" asp-controller="ProductDetails" asp-route-articleNumber="@product.ArticleNumber" class="collection-item">
                    <img class="poster-image" src="@product.ImageUrl" alt="Posters">
                    <div class="body">
                        <div class="title"> @product.ProductName</div>
                        <div class="info">
                            <div class="price">@product.Price SEK</div>
                            <i class="add-cart fa-solid fa-cart-plus"></i>
                        </div>
                    </div>
                </a>

            }
        </div>

        
    </div>
</section>

Views/Partials/_Registration.cshtml
@model RegisterViewModel

<div class="container">
    <div class="register-container">
    <div class="col-6">
        <form asp-action="Index" asp-controller="Registration" method="post" novalidate>
            <div class="mb-3">
                <label asp-for="FirstName" class="form-label"></label>
                <input asp-for="FirstName" class="form-control" onkeyup="validateText" />
                <small><span asp-validation-for="FirstName" class="text-danger"></span></small>
            </div>

            <div class="mb-3">
                <label asp-for="LastName" class="form-label"></label>
                <input asp-for="LastName" class="form-control" onkeyup="validateText" />
                <small><span asp-validation-for="LastName" class="text-danger"></span></small>
            </div>

            <div class="mb-3">
                <label asp-for="Email" class="form-label"></label>
                <input asp-for="Email" class="form-control" onkeyup="validateEmail" />
                <small><span asp-validation-for="Email" class="text-danger"></span></small>
            </div>

            <div class="mb-3">
                <label asp-for="Password" class="form-label"></label>
                <input asp-for="Password" class="form-control" onkeyup="validatePassword" />
                <small><span asp-validation-for="Password" class="text-danger"></span></small>
            </div>

            <div class="mb-3">
                <label asp-for="StreetName" class="form-label"></label>
                <input asp-for="StreetName" class="form-control" onkeyup="validateText" />
                <small><span asp-validation-for="StreetName" class="text-danger"></span></small>
            </div>
            <div class="mb-3">
                <label asp-for="PostalCode" class="form-label"></label>
                <input asp-for="PostalCode" class="form-control" onkeyup="validateText" />
                <small><span asp-validation-for="PostalCode" class="text-danger"></span></small>
            </div>
            <div class="mb-3">
                <label asp-for="City" class="form-label"></label>
                <input asp-for="City" class="form-control" onkeyup="validateText" />
                <small><span asp-validation-for="City" class="text-danger"></span></small>
            </div>

            <div class="d-grid mb-5">
                <button type="submit" class="btn btn-success mt-2">Register</button>
            </div>

        </form>
    </div>
    </div>
</div>

Views/Partials/_UserProfilePage.cshtml
<div class="container">
    <div class="d-flex justify-content-center align-items-center min-vh-100">
        <div class="col-6">
            <div class="access-denied-wrapper">
                <div class="access-denied">
                This is your profile page.
                </div>
            </div>
        </div>

    </div>
</div>